### ISSUE TITLE
Fix entities/ents loading? Or do they work

### ISSUE THREAD

**Issue by timbergeron** [quakeone/crmod-plus#21]

**Comment by sputnikutah** [comment]
i need to rewrite this part, as the old way was using alias commands (server-side) to read files ("exec map.ent")

**Comment by inf1niti** [comment]
bit of work done (temporarily commented out ENT handlers) in [6bfded8](https://github.com/quakeone/crmod-plus/commit/6bfded81129314614aa71e44458c9ded84fcb0bb)

**Comment by inf1niti** [comment]
accidentally left ent files on the server for aerowalk, and it was crashing the server on attempted load.

**Comment by sputnikutah** [comment]
crmod is using, unused client cvars to store values of origin and angle for the created entity
and the dedicated server doesnt have these cvars so they fail. 
the server qss/fte already handles .ent files so doing it in the mod is outdated.
