### ISSUE TITLE
Make warping easier like ezquake

### ISSUE THREAD

**Issue by timbergeron** [quakeone/crmod-plus#22]
for anymap on the server I can just type the map bsp name to initiate a vote. make aliases for all the maps. this skips having to type 3 things vs one

**Comment by inf1niti** [comment]
I agree with this task, but I think the KTX/MDVSV solution is not the right way to go with this.  

Some of the problems I have with the QW approach:
- It's difficult to see a list of what maps are available on the server
- it's one big list of bsp filenames, which are often non descriptive
- lacking map metadata & categorization.  It would be nice to have a mechanism for filtering or seeing details on each map.

**Comment by timbergeron** [comment]
Sorry replied via email and all that got quoted

**Comment by inf1niti** [comment]
no worries :)
