### ISSUE TITLE
time limit voting automatic

### ISSUE THREAD

**Issue by timbergeron** [quakeone/crmod-plus#35]
Server setting option from admin to make time limit voting automatic so it doesn’t need a vote.

**Comment by sputnikutah** [comment]
im not sure i understand the request

**Comment by timbergeron** [comment]
Anyone on the server can change the time limit if in match mode; it wouldn't need a vote. Matches are organized by players as is and this makes it easier. This would be a server setting that the admin could configure to allow on her/his server.
