### ISSUE TITLE
2 & 3 arg mode change

### ISSUE THREAD

**Issue by timbergeron** [quakeone/crmod-plus#37]
Allow mod chang commands to take 3 arguments:

Dm normal dm6
Ctf match ctf3m2
Ctf practice ctf8

**Comment by inf1niti** [comment]
should we support 2 arg as well?  Any combination?

ie `dm dm6`, `match ctf3m2`, `ctf practice`?

**Comment by timbergeron** [comment]
Ya two arg as well
