### ISSUE TITLE
[QSS-M] cannot connect: `scv_updatename > MAX_SCOREBOARD`

### ISSUE THREAD

**Issue by inf1niti** [quakeone/crmod-plus#43]
more than one person has got this in QSS-M intermittently.  Happens on build 1.4.1 as well, regardless of whether the `...`/`afk` name issue is present for the player, on any other player on the server.

![image](https://user-images.githubusercontent.com/67801374/150904633-31e1d565-99df-4b5a-bca8-fc278a07af43.png)

**Comment by sputnikutah** [comment]
it seems in score_fix_connect in score.qc, there was a typo
score_write_name(self.colormap, "");
should be
score_write_name(self.colormap - 1, "");//FIXED? (issue #43) (edited)
[12:33 PM]
weird that bug still exists in crmod 6.6

**Comment by inf1niti** [comment]
fixed in commit [cbcf651](https://github.com/quakeone/crmod-plus/commit/cbcf6513dce6895070188c518bca330c3dc07a75)
