### ISSUE TITLE
shownick like qw

### ISSUE THREAD

**Issue by timbergeron** [quakeone/crmod-plus#5]

**Comment by timbergeron** [comment]
![Xvche7H](https://user-images.githubusercontent.com/68674590/150902383-c962da06-a652-4a58-9571-6e7626b22bdd.png)

**Comment by inf1niti** [comment]
I don't think it's supposed to show data for enemies - is this correct?

**Comment by timbergeron** [comment]
Only teammates

--
Tim Bergeron
timbergeron.com

**Comment by timbergeron** [comment]
This is great if I am at the RA with someone. 1) I know who it is so if its Chris I def let him have it, and 2) to see if they have weapons without reading their binds (if they are reporting or not)
