### ISSUE TITLE
ready? announces to all players

### ISSUE THREAD

**Issue by timbergeron** [quakeone/crmod-plus#53]

**Comment by sputnikutah** [comment]
dont we have ready on the scoreboard? who uses `ready?` anymore.

**Comment by timbergeron** [comment]
It's a more polite way to tell someone to ready up

**Comment by sputnikutah** [comment]
ya i see, just type `ready?` and the mod prints to screen "These players are not ready: ..."
or like in CA "PLAYER is holding things up!"

**Comment by inf1niti** [comment]
fixed in [e715555](https://github.com/quakeone/crmod-plus/commit/e71555526b9f3780b5e9294f5d5a0d11d6608b70)
